Content-Type: application/json

### Create Region
POST localhost:8080/region
{
  "orderNumber": "Asuna",
  "nameUz": "Yuuki",
  "nameEn": "Yuuki",
  "nameRu": "Yuuki",
}

### Update Region
PUT localhost:8080/region/1
{
  "orderNumber": "Asuna",
  "nameUz": "Yuuki",
  "nameEn": "Yuuki",
  "nameRu": "Yuuki",
}

### Delete Region
DELETE localhost:8080/region/1

### Get ArticleiType List
GET localhost:8080/region?page=1&size=10

### Get ArticleiType List by Lang
GET localhost:8080/region/uz/1